[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.12"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/auth/login/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
